name: Check & Create PR

on:
  push:
    branches:
      - dev
    
jobs: 
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      lenPrs: ${{ steps.check_pr.outputs.lenPrs }}
      isInitialCommit: ${{ steps.check_pr.outputs.isInitialCommit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          
      - id: check_pr
        name: Check PR list
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ref: ${{ github.ref_name }}
        run: |
          if [[ $ref == 'dev' ]]; then
            lenPrs=$(gh pr list -B prod -H dev --json id,title --jq '. | length')
            echo "lenPrs=$lenPrs" >> "$GITHUB_OUTPUT"
          else
            echo "not implemented yet"
          fi

          echo "Checking if is initial commit..."

          isInitialCommit=$(git log --oneline -n 3 | grep -o "Initial commit" | wc -l)

          echo "Should be 1 if is initial commit: $isInitialCommit"

          echo $isInitialCommit
          echo "isInitialCommit=$isInitialCommit" >> "$GITHUB_OUTPUT"


           
  create-pr-prod:
    needs: check_pr
    if: ${{ github.ref_name == 'dev' && needs.check_pr.outputs.lenPrs == 0 && needs.check_pr.outputs.isInitialCommit == 1}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          
      - name: Create PR dev into prod  
        env:
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            reviewers=$(gh api "repos/$repo/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
            gh pr create -B prod -H dev --title "Merge branch dev -> prod - Criado Automatico" --body "Criado Automaticamente" --reviewer "$reviewers"
